package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunCategory;
import com.jindouyun.db.domain.JindouyunCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    long countByExample(JindouyunCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int insert(JindouyunCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    List<JindouyunCategory> selectByExample(JindouyunCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    JindouyunCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunCategory record, @Param("example") JindouyunCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunCategory record, @Param("example") JindouyunCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunCategory record);
}