package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunGrabOrder;
import com.jindouyun.db.domain.JindouyunGrabOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunGrabOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    long countByExample(JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int insert(JindouyunGrabOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunGrabOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    JindouyunGrabOrder selectOneByExample(JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    JindouyunGrabOrder selectOneByExampleSelective(@Param("example") JindouyunGrabOrderExample example, @Param("selective") JindouyunGrabOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    List<JindouyunGrabOrder> selectByExampleSelective(@Param("example") JindouyunGrabOrderExample example, @Param("selective") JindouyunGrabOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    List<JindouyunGrabOrder> selectByExample(JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    JindouyunGrabOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunGrabOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    JindouyunGrabOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    JindouyunGrabOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunGrabOrder record, @Param("example") JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunGrabOrder record, @Param("example") JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunGrabOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunGrabOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunGrabOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_grab_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}