package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunAdmin;
import com.jindouyun.db.domain.JindouyunAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    long countByExample(JindouyunAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int insert(JindouyunAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    List<JindouyunAdmin> selectByExample(JindouyunAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    JindouyunAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunAdmin record, @Param("example") JindouyunAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunAdmin record, @Param("example") JindouyunAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunAdmin record);
}