package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunGoodsProduct;
import com.jindouyun.db.domain.JindouyunGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    long countByExample(JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int insert(JindouyunGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    JindouyunGoodsProduct selectOneByExample(JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    JindouyunGoodsProduct selectOneByExampleSelective(@Param("example") JindouyunGoodsProductExample example, @Param("selective") JindouyunGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    List<JindouyunGoodsProduct> selectByExampleSelective(@Param("example") JindouyunGoodsProductExample example, @Param("selective") JindouyunGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    List<JindouyunGoodsProduct> selectByExample(JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    JindouyunGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    JindouyunGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    JindouyunGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunGoodsProduct record, @Param("example") JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunGoodsProduct record, @Param("example") JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}