package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunGoodsSpecification;
import com.jindouyun.db.domain.JindouyunGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int insert(JindouyunGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    JindouyunGoodsSpecification selectOneByExample(JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    JindouyunGoodsSpecification selectOneByExampleSelective(@Param("example") JindouyunGoodsSpecificationExample example, @Param("selective") JindouyunGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    List<JindouyunGoodsSpecification> selectByExampleSelective(@Param("example") JindouyunGoodsSpecificationExample example, @Param("selective") JindouyunGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    List<JindouyunGoodsSpecification> selectByExample(JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    JindouyunGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    JindouyunGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    JindouyunGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunGoodsSpecification record, @Param("example") JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunGoodsSpecification record, @Param("example") JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}