package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunDeliveryStaff;
import com.jindouyun.db.domain.JindouyunDeliveryStaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunDeliveryStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    long countByExample(JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int insert(JindouyunDeliveryStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunDeliveryStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    JindouyunDeliveryStaff selectOneByExample(JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    JindouyunDeliveryStaff selectOneByExampleSelective(@Param("example") JindouyunDeliveryStaffExample example, @Param("selective") JindouyunDeliveryStaff.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    List<JindouyunDeliveryStaff> selectByExampleSelective(@Param("example") JindouyunDeliveryStaffExample example, @Param("selective") JindouyunDeliveryStaff.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    List<JindouyunDeliveryStaff> selectByExample(JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    JindouyunDeliveryStaff selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunDeliveryStaff.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    JindouyunDeliveryStaff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    JindouyunDeliveryStaff selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunDeliveryStaff record, @Param("example") JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunDeliveryStaff record, @Param("example") JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunDeliveryStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunDeliveryStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunDeliveryStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_delivery_staff
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}