package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunRegisteDeliveries;
import com.jindouyun.db.domain.JindouyunRegisteDeliveriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunRegisteDeliveriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    long countByExample(JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int insert(JindouyunRegisteDeliveries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunRegisteDeliveries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    JindouyunRegisteDeliveries selectOneByExample(JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    JindouyunRegisteDeliveries selectOneByExampleSelective(@Param("example") JindouyunRegisteDeliveriesExample example, @Param("selective") JindouyunRegisteDeliveries.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    List<JindouyunRegisteDeliveries> selectByExampleSelective(@Param("example") JindouyunRegisteDeliveriesExample example, @Param("selective") JindouyunRegisteDeliveries.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    List<JindouyunRegisteDeliveries> selectByExample(JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    JindouyunRegisteDeliveries selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunRegisteDeliveries.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    JindouyunRegisteDeliveries selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    JindouyunRegisteDeliveries selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunRegisteDeliveries record, @Param("example") JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunRegisteDeliveries record, @Param("example") JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunRegisteDeliveries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunRegisteDeliveries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunRegisteDeliveriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_deliveries
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}