package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunRole;
import com.jindouyun.db.domain.JindouyunRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    long countByExample(JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int insert(JindouyunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    JindouyunRole selectOneByExample(JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    JindouyunRole selectOneByExampleSelective(@Param("example") JindouyunRoleExample example, @Param("selective") JindouyunRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    List<JindouyunRole> selectByExampleSelective(@Param("example") JindouyunRoleExample example, @Param("selective") JindouyunRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    List<JindouyunRole> selectByExample(JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    JindouyunRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    JindouyunRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    JindouyunRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunRole record, @Param("example") JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunRole record, @Param("example") JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}