package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunDeliveriesPerformance;
import com.jindouyun.db.domain.JindouyunDeliveriesPerformanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunDeliveriesPerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    long countByExample(JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int insert(JindouyunDeliveriesPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunDeliveriesPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    JindouyunDeliveriesPerformance selectOneByExample(JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    JindouyunDeliveriesPerformance selectOneByExampleSelective(@Param("example") JindouyunDeliveriesPerformanceExample example, @Param("selective") JindouyunDeliveriesPerformance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    List<JindouyunDeliveriesPerformance> selectByExampleSelective(@Param("example") JindouyunDeliveriesPerformanceExample example, @Param("selective") JindouyunDeliveriesPerformance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    List<JindouyunDeliveriesPerformance> selectByExample(JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    JindouyunDeliveriesPerformance selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunDeliveriesPerformance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    JindouyunDeliveriesPerformance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    JindouyunDeliveriesPerformance selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunDeliveriesPerformance record, @Param("example") JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunDeliveriesPerformance record, @Param("example") JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunDeliveriesPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunDeliveriesPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunDeliveriesPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_deliveries_performance
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}