package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunRegisteBrand;
import com.jindouyun.db.domain.JindouyunRegisteBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunRegisteBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    long countByExample(JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int insert(JindouyunRegisteBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunRegisteBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    JindouyunRegisteBrand selectOneByExample(JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    JindouyunRegisteBrand selectOneByExampleSelective(@Param("example") JindouyunRegisteBrandExample example, @Param("selective") JindouyunRegisteBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    List<JindouyunRegisteBrand> selectByExampleSelective(@Param("example") JindouyunRegisteBrandExample example, @Param("selective") JindouyunRegisteBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    List<JindouyunRegisteBrand> selectByExample(JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    JindouyunRegisteBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunRegisteBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    JindouyunRegisteBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    JindouyunRegisteBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunRegisteBrand record, @Param("example") JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunRegisteBrand record, @Param("example") JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunRegisteBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunRegisteBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunRegisteBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_registe_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}