package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunCart;
import com.jindouyun.db.domain.JindouyunCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    long countByExample(JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int insert(JindouyunCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    JindouyunCart selectOneByExample(JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    JindouyunCart selectOneByExampleSelective(@Param("example") JindouyunCartExample example, @Param("selective") JindouyunCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    List<JindouyunCart> selectByExampleSelective(@Param("example") JindouyunCartExample example, @Param("selective") JindouyunCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    List<JindouyunCart> selectByExample(JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    JindouyunCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    JindouyunCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    JindouyunCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunCart record, @Param("example") JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunCart record, @Param("example") JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}