package com.jindouyun.db.dao;

import com.jindouyun.db.domain.JindouyunLog;
import com.jindouyun.db.domain.JindouyunLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JindouyunLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    long countByExample(JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int deleteByExample(JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int insert(JindouyunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int insertSelective(JindouyunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    JindouyunLog selectOneByExample(JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    JindouyunLog selectOneByExampleSelective(@Param("example") JindouyunLogExample example, @Param("selective") JindouyunLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    List<JindouyunLog> selectByExampleSelective(@Param("example") JindouyunLogExample example, @Param("selective") JindouyunLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    List<JindouyunLog> selectByExample(JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    JindouyunLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JindouyunLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    JindouyunLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    JindouyunLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JindouyunLog record, @Param("example") JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JindouyunLog record, @Param("example") JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JindouyunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JindouyunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JindouyunLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jindouyun_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}