spring:
  profiles:
    active: db, core, delivery
  messages:
    encoding: UTF-8

server:
  port: 8084

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.jindouyun.delivery:  DEBUG
    com.jindouyun:  ERROR